name=M5Echo-Pyramid
version=1.0.0
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack M5Echo-Pyramid
paragraph=M5Stack, M5Echo-Pyramid, See more on http://m5stack.com
category=Sensor
url=https://github.com/m5stack/M5Echo-Pyramid.git
architectures=esp32
includes=M5EchoPyramid.h